# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:              JGobeil 
tagline:             'Notes de cours et autres'
description:         ''
url:                 http://jgobeil.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Jérémie Gobeil
  url:               https://jgobeil.github.io
  email:             jeremie.gobeil@gmail.com

# Custom vars
version:             1.0.0
